##### Building stage #####
FROM nvidia/cuda:12.3.1-devel-ubuntu22.04 as builder
MAINTAINER Kieran Harkin <kieran+git@harkin.me>

# Versions of nginx, rtmp-module and ffmpeg 
ENV  TZ=Europe/Dublin
ARG  NGINX_VERSION=1.29.4
ARG  NGINX_RTMP_MODULE_VERSION=master
ARG  FFMPEG_VERSION=8.0.1

# Install dependencies
RUN apt-get update && \
	apt-get install -y --no-install-recommends \
		wget gcc make autoconf automake ca-certificates \
		openssl libssl-dev yasm git pkg-config nasm zlib1g-dev \
		libpcre3-dev librtmp-dev libtheora-dev libvorbis-dev \
		libvpx-dev libfreetype6-dev libmp3lame-dev libx264-dev libx265-dev && \
    rm -rf /var/lib/apt/lists/*

# Download nginx source
RUN mkdir -p /tmp/build && \
	cd /tmp/build && \
	wget https://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz && \
	tar -zxf nginx-${NGINX_VERSION}.tar.gz && \
	rm nginx-${NGINX_VERSION}.tar.gz

# Download rtmp-module source
RUN cd /tmp/build && \
    wget https://github.com/arut/nginx-rtmp-module/archive/${NGINX_RTMP_MODULE_VERSION}.tar.gz && \
    tar -zxf ${NGINX_RTMP_MODULE_VERSION}.tar.gz && \
	rm ${NGINX_RTMP_MODULE_VERSION}.tar.gz

# Build nginx with nginx-rtmp module
RUN cd /tmp/build/nginx-${NGINX_VERSION} && \
    ./configure \
        --prefix=/app/nginx \
        --conf-path=/etc/nginx/nginx.conf \
        --error-log-path=/var/log/nginx/error.log \
        --http-log-path=/var/log/nginx/access.log \		
        --pid-path=/var/run/nginx/nginx.pid \
        --lock-path=/var/lock/nginx.lock \
        --http-client-body-temp-path=/tmp/nginx-client-body \
        --with-http_ssl_module \
        --with-threads \
        --add-module=/tmp/build/nginx-rtmp-module-${NGINX_RTMP_MODULE_VERSION} \
        --with-cc-opt="-Wimplicit-fallthrough=0" && \
    make -j $(getconf _NPROCESSORS_ONLN) && \
    make install

# Download ffmpeg source
RUN cd /tmp/build && \
  wget http://ffmpeg.org/releases/ffmpeg-${FFMPEG_VERSION}.tar.gz && \
  tar -zxf ffmpeg-${FFMPEG_VERSION}.tar.gz && \
  rm ffmpeg-${FFMPEG_VERSION}.tar.gz
  
# Get ffnvcodec
RUN git clone https://git.videolan.org/git/ffmpeg/nv-codec-headers.git && \
  cd nv-codec-headers && \
  make -j $(getconf _NPROCESSORS_ONLN) && \
  make install
  
# Build ffmpeg
RUN cd /tmp/build/ffmpeg-${FFMPEG_VERSION} && \
  ./configure \
          --prefix=/app/ffmpeg \
	  --enable-version3 \
	  --enable-gpl \
	  --enable-nonfree \
	  --enable-small \
	  --enable-libx264 \
	  --enable-libx265 \
	  --enable-libvpx \
	  --enable-libtheora \
	  --enable-libvorbis \
	  --enable-librtmp \
	  --enable-postproc \
	  --enable-swresample \ 
	  --enable-libfreetype \
	  --enable-libmp3lame \
	  --enable-cuda \
	  --enable-cuvid \
	  --enable-nvenc \
	  --enable-libnpp \
	  --extra-cflags=-I/usr/local/cuda/include  \
	  --extra-ldflags=-L/usr/local/cuda/lib64 \
	  --disable-debug \
	  --disable-doc \
	  --disable-ffplay \
	  --extra-libs="-lpthread -lm" && \
	make -j $(getconf _NPROCESSORS_ONLN) && \
	make install
	
# Copy stats.xsl file to nginx html directory and cleaning build files
RUN cp /tmp/build/nginx-rtmp-module-${NGINX_RTMP_MODULE_VERSION}/stat.xsl /app/nginx/html/stat.xsl && \
	rm -rf /tmp/build

##### Building the final image #####
FROM nvidia/cuda:12.3.1-runtime-ubuntu22.04

ENV  NVIDIA_DRIVER_CAPABILITIES compute,video,utility

#Setup nvidia-patch
COPY patch.sh docker-entrypoint.sh /app/
RUN mkdir -p /patched-lib && \
  chmod +x /app/patch.sh /app/docker-entrypoint.sh && \
  ln -s /app/patch.sh /usr/local/bin/patch.sh

# Install dependencies
RUN apt-get update && \
	apt-get install -y --no-install-recommends \
		ca-certificates openssl libpcre3-dev \
		librtmp1 libtheora0 libvorbis0a libmp3lame0 \
		libvpx7 libx264-dev libx265-dev && \
    rm -rf /var/lib/apt/lists/*

# Copy files from build stage to final stage	
COPY --from=builder /app /app
COPY --from=builder /etc/nginx /etc/nginx

# Copy configuration
COPY conf/nginx-nvenc.conf /etc/nginx/nginx.conf

# Create logs directory
RUN mkdir -p /var/log/nginx

# Expose RTMP and HTTP ports
EXPOSE 1935 8080

# Command to run nginx
CMD ["/app/docker-entrypoint.sh"]
